variables:
    DOCKER_USERNAME: naticadevelopment
    DOCKER_TAG: latest

stages:
    - test
    - build
    - deploy
    - google

run_test:
    stage: test
    image: node:16-alpine
    before_script:
        - apk upgrade && apk add yarn
        - yarn install
    script:
        - yarn test --ci

run_build:
    stage: build
    image: docker:20.10.17
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
        SHA: $(git rev-parse HEAD)
    services:
        - docker:20.10.17-dind
    before_script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - chmod 700 ./containers/deploy.sh
    script:
        - sh ./containers/deploy.sh
    
