workflow:
    rules:
        - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
          when: never
        - when: always

variables:
    DOCKER_USERNAME: naticadevelopment
    DOCKER_LATEST_TAG: latest
    CURRENT_TAG: $CI_PIPELINE_IID
    CONTAINER_DIR: ./containers/Dockerfile

stages:
    - test
    - build
    - deploy

sast:
    stage: test

run_test:
    stage: test
    image: node:16-alpine
    before_script:
        - apk update && apk add yarn
        - yarn install
    script:
        - yarn test --ci

    except:
        - main

run_build:
    stage: build
    image: docker:20.10.17-alpine3.16
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    services:
        - docker:20.10.17-dind-alpine3.16
    before_script:
        - apk update
        - apk add git
        - export HEAD=$(git rev-parse HEAD)
        - echo $DOCKER_USER
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    script:
        - docker buildx build -f $CONTAINER_DIR . --platform=linux/amd64 -t $DOCKER_USERNAME/prod_server:$DOCKER_LATEST_TAG -t $DOCKER_USERNAME/prod_server:$HEAD --push
        - docker buildx build -f $CONTAINER_DIR . --platform=linux/amd64 -t $DOCKER_USERNAME/prod_db:$DOCKER_LATEST_TAG -t $DOCKER_USERNAME/prod_db:$HEAD --push
    only:
        - main

deploy_to_eks:
    stage: deploy
    image: docker:20.10.17-alpine3.16
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    services:
        - docker:20.10.17-dind-alpine3.16
    script:
        - env
    extends:
        - .run_aws_login
    only:
        - main

.run_aws_login:
    stage: deploy
    image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base
    script:
        - echo $(aws secretsmanager get-secret-value --secret-id "prod/bastaci/db-env" --query SecretString --output text | jq 'to_entries|map("\(.key)=\(.value)")|.[]' -r | grep -v "#" |  sed 's/\r$//' | awk '/=/ {print $1}') > build.env

    artifacts:
        reports:
            dotenv: build.env

include:
    - template: Jobs/SAST.latest.gitlab-ci.yml
