variables:
    DOCKER_USERNAME: naticadevelopment
    DOCKER_LATEST_TAG: latest

stages:
    - test
    - build
    - deploy

run_test:
    stage: test
    image: node:16-alpine
    before_script:
        - apk upgrade && apk add yarn
        - yarn install
    script:
        - yarn test --ci

run_build:
    stage: build
    image: docker:20.10.17
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    services:
        - docker:20.10.17-dind
    before_script:
        - apk upgrade
        - apk add git
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    script:
        - docker buildx build . --platform=linux/amd64 -t $DOCKER_USERNAME/prod_server:$DOCKER_LATEST_TAG -t $DOCKER_USERNAME/prod_server:$(git rev-parse HEAD) --push
        - docker buildx build . --platform=linux/amd64 -t $DOCKER_USERNAME/prod_db:$DOCKER_LATEST_TAG -t $DOCKER_USERNAME/prod_db:$(git rev-parse HEAD) --push