workflow:
    rules:
        - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
          when: never
        - when: always

variables:
    DOCKER_USERNAME: naticadevelopment
    DOCKER_LATEST_TAG: latest
    CURRENT_TAG: $CI_PIPELINE_IID
    CONTAINER_DIR: ./containers/Dockerfile

stages:
    - test
    - build
    - deploy

sast:
    stage: test

run_test:
    stage: test
    image: node:16-alpine
    before_script:
        - apk update && apk add yarn
        - yarn install
    script:
        - yarn test --ci

    except:
        - main

run_build:
    stage: build
    image: docker:20.10.17-alpine3.16
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    services:
        - docker:20.10.17-dind-alpine3.16
    before_script:
        - apk update
        - apk add git
        - export HEAD=$(git rev-parse HEAD)
        - echo $DOCKER_USER
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    script:
        - docker buildx build -f $CONTAINER_DIR . --platform=linux/amd64 -t $DOCKER_USERNAME/prod_server:$DOCKER_LATEST_TAG -t $DOCKER_USERNAME/prod_server:$HEAD --push
        - docker buildx build -f $CONTAINER_DIR . --platform=linux/amd64 -t $DOCKER_USERNAME/prod_db:$DOCKER_LATEST_TAG -t $DOCKER_USERNAME/prod_db:$HEAD --push
    only:
        - main

run_aws_login:
    stage: deploy
    image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base
    script:
        - echo $(aws secretsmanager get-secret-value --secret-id "prod/bastaci/db-env" --query SecretString --output text | jq 'to_entries|map("\(.key)=\(.value)")|.[]' -r | grep -v "#" |  sed 's/\r$//' | awk '/=/ {print $1}') > build.env
    artifacts:
        reports:
            dotenv: build.env
        paths:
            - ""
    only:
        - main

run_eks_deploy:
    stage: deploy
    image: lwolf/helm-kubectl-docker:v152_213
    before_script:
        - mkdir -p /etc/deploy
        - echo ${kube_config} | base64 -d > ${KUBECONFIG}
    script:
        - cd deploy/libr-files
        - helm dep build
        - export API_VERSION="$(grep "appVersion" Chart.yaml | cut -d" " -f2)"
        - export RELEASE_NAME="libr-files-v${API_VERSION/./-}"
        - export DEPLOYS=$(helm ls | grep $RELEASE_NAME | wc -l)
        - if [ ${DEPLOYS}  -eq 0 ]; then helm install --name=${RELEASE_NAME} . --namespace=${STAGING_NAMESPACE}; else helm upgrade ${RELEASE_NAME} . --namespace=${STAGING_NAMESPACE}; fi
    environment:
        name: production
        url: https://natica-handshake.com
    only:
        - main

include:
    - template: Jobs/SAST.latest.gitlab-ci.yml
