workflow:
    rules:
        - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
          when: never
        - when: always

variables:
    DOCKER_USERNAME: naticadevelopment
    DOCKER_LATEST_TAG: latest
    CURRENT_TAG: $CI_PIPELINE_IID
    CONTAINER_DIR: ./containers/Dockerfile
    ROOT_USER: ec2-user

stages:
    - test
    - image_build_and_deploy
    - aws_secret_set
    - validate_eks_infrastructure
    - eks_infrastructure_provision
    - eks_deploy
    - basttion_prep
    - destroy

sast:
    stage: test

run_test:
    stage: test
    image: node:16-alpine
    before_script:
        - apk update && apk add yarn
        - yarn install
    script:
        - yarn test --ci

    except:
        - main

run_build_and_deploy:
    stage: image_build_and_deploy
    image: docker:20.10.17-alpine3.16
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    services:
        - docker:20.10.17-dind-alpine3.16
    before_script:
        - apk update
        - apk add git
        - export HEAD=$(git rev-parse HEAD)
        - echo $DOCKER_USER
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    script:
        - docker buildx build -f $CONTAINER_DIR . --platform=linux/amd64 -t $DOCKER_USERNAME/prod_server:$DOCKER_LATEST_TAG -t $DOCKER_USERNAME/prod_server:$HEAD --push
        - docker buildx build -f $CONTAINER_DIR . --platform=linux/amd64 -t $DOCKER_USERNAME/prod_db:$DOCKER_LATEST_TAG -t $DOCKER_USERNAME/prod_db:$HEAD --push
    only:
        - main

run_secret_envs:
    stage: aws_secret_set
    image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base
    script:
        - echo $(aws secretsmanager get-secret-value --secret-id "prod/bastaci/db-env" --query SecretString --output text | jq 'to_entries|map("\(.key)=\(.value)")|.[]' -r | grep -v "#" |  sed 's/\r$//' | awk '/=/ {print $1}') > build.env
    artifacts:
        reports:
            dotenv: build.env
    only:
        - main

image:
    name: hashicorp/terraform:light
    entrypoint:
        - "/usr/bin/env"
        - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
        - "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
        - "AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}"

run_provision_valid:
    stage: validate_eks_infrastructure
    script:
        - cd ./terraform
        - rm -rf .terraform
        - terraform --version
        - terraform init
        - terraform validate
        - terraform plan
    only:
        - main

run_eks_infrastructure_provision:
    stage: eks_infrastructure_provision
    script:
        - cd ./terraform
        - rm -rf .terraform
        - terraform --version
        - terraform init
        - terraform validate
        - terraform plan
        - terraform apply -auto-approve=true
        - cd ../
        - EC2_BASTION_IP=$(terraform output -json bastion_eip | awk -F'[(")]' '{print $2}') >> deploy.env
    artifacts:
        reports:
            dotenv: deploy.env

    only:
        - main

run_eks_deploy:
    stage: eks_deploy
    when: manual
    extends: run_eks_infrastructure_provision
    script:
        - mkdir -p ~/.ssh && chmod 700 ~/.ssh
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa
        - eval $(ssh-agent -s)
        - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
        # waiting for completing to install shh
        - sleep 200
        - ssh -T -o "StrictHostKeyChecking no" -l $ROOT_USER $EC2_BASTION_IP "sudo DEBIAN_FRONTEND=noninteractive apt -y update"
        - ssh -T -o "StrictHostKeyChecking no" -l $ROOT_USER $EC2_BASTION_IP "sudo DEBIAN_FRONTEND=noninteractive apt -y install unzip"
        - ssh -T -o "StrictHostKeyChecking no" -l $ROOT_USER $EC2_BASTION_IP "curl 'https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip' -o awscliv2.zip && unzip awscliv2.zip"
        - ssh -T -o "StrictHostKeyChecking no" -l $ROOT_USER $EC2_BASTION_IP "sudo ./aws/install"

        - ssh -T -o "StrictHostKeyChecking no" -l $ROOT_USER $EC2_BASTION_IP "aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}"
        - ssh -T -o "StrictHostKeyChecking no" -l $ROOT_USER $EC2_BASTION_IP "aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}"
        - ssh -T -o "StrictHostKeyChecking no" -l $ROOT_USER $EC2_BASTION_IP "aws configure set default.region $AWS_DEFAULT_REGION"
        - ssh -T -o "StrictHostKeyChecking no" -l $ROOT_USER $EC2_BASTION_IP "aws --version"

        - ssh -T -o "StrictHostKeyChecking no" -l $ROOT_USER $EC2_BASTION_IP "curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.2/bin/linux/amd64/kubectl"
        - ssh -T -o "StrictHostKeyChecking no" -l $ROOT_USER $EC2_BASTION_IP "chmod +x ./kubectl && sudo mv ./kubectl /usr/local/bin/kubectl"
        - ssh -T -o "StrictHostKeyChecking no" -l $ROOT_USER $EC2_BASTION_IP "aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name $(terraform output -json cluster_name | awk -F'[(")]' '{print $2}')"
        - scp -r ./eks $ROOT_USER@$EC2_BASTION_IP:~/
        - ssh -T -o "StrictHostKeyChecking no" -l $ROOT_USER $EC2_BASTION_IP "kubectl apply -f ~/eks/aws-auth.yaml"
        - ssh -T -o "StrictHostKeyChecking no" -l $ROOT_USER $EC2_BASTION_IP "kubectl apply -f ~/eks/container-secret.yaml"
        - ssh -T -o "StrictHostKeyChecking no" -l $ROOT_USER $EC2_BASTION_IP "kubectl apply -f ~/eks "

    only:
        - main

run_eks_destroy:
    when: manual
    stage: destroy
    script:
        - terraform destroy -auto-approve
    only:
        - main

run_eks_destroy:
    when: manual
    script:
        - terraform destroy -auto-approve

include:
    - template: Jobs/SAST.latest.gitlab-ci.yml
