version: '3.8'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis/data
volumes:
  pgdata:
  redis:
