FROM node:16-alpine AS devbase


WORKDIR /usr/devapi


COPY ./package.json /usr/devapi/
COPY ./yarn.lock /usr/devapi/

RUN yarn install 

COPY ./ /usr/devapi/

RUN yarn prepare

FROM devbase as devbuild 

RUN pwd


