version: "3.8"
services:
  db_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev.postgres

    container_name: postgres_dev
    command:
      [
        "postgres",
        "-c",
        "log_statement=all",
        "-c",
        "log_destination=stderr"
      ]

    restart: always
    env_file:
      - ./.env.test
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - pgdata:${PGDATA}

  redis_dev:
    image: redis:6.2.6-alpine
    container_name: redis_dev
    restart: always
    env_file:
      - ./.env.test
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redisdata:/var/lib/redis/data

  dev_server:
    build:
      context: .
      target: devbase

    container_name: dev_server

    env_file:
      - ./.env.test
    volumes:
      - /usr/api/node_modules
      - ./:/usr/api

    expose:
      - "${SERVER_PORT}"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

    command: yarn devrunner

volumes:
  pgdata:
  redisdata:
