version: "3.8"
services:
  db_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod.postgres

    container_name: db_prod
    restart: always
    env_file:
      - ./.env
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - pgdata:${PGDATA}

  redis_prod:
    image: redis:6.2.6-alpine
    container_name: redis_prod
    env_file:
      - ./.env

    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redisdata:/var/lib/redis/data

  prod_server:
    build:
      context: .
      target: prodbase
    container_name: prod_server

    env_file:
      - ./.env

    expose:
      - "8080"
    ports:
      - "8080:8080"
volumes:
  pgdata:
  redisdata:
