FROM postgres:14-alpine

WORKDIR /

COPY ./wait-for.sh ./

COPY ./postgresql.conf /etc/postgresql/postgresql.conf

COPY ./src/seeds/restore_db.sh /docker-entrypoint-initdb.d/

COPY ./src/seeds/database.sql /docker-entrypoint-initdb.d/
