version: "3.9"
services:
  db_dev:
    build:
      context: ${PWD}
      dockerfile: ${PWD}/containers/Dockerfile.dev.postgres

    container_name: postgres_dev
    command:
      [
        "postgres",
        "-c",
        "log_statement=all",
        "-c",
        "log_destination=stderr"
      ]

    restart: always
    env_file:
      - ${PWD}/.env.test
    environment:
      PG_PORT: ${PG_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_DATA: ${PGDATA}

    ports:
      - "${PG_PORT}:${PG_PORT}"
    volumes:
      - pgdata:${PGDATA}

  dev_server:
    build:
      context: ${PWD}
      dockerfile: ${PWD}/containers/Dockerfile
      target: devbase

    container_name: dev_server

    env_file:
      - ${PWD}/.env.test
    volumes:
      - /usr/api/node_modules
      - ${PWD}:/usr/api

    expose:
      - "${SERVER_PORT}"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

    depends_on:
      - db_dev

    entrypoint:
      [
        "/usr/api/wait-for.sh",
        "db_dev:${PG_PORT}",
        "--",
        "yarn",
        "devrunner"
      ]
    command: yarn devrunner

volumes:
  pgdata:
