apiVersion: v1
kind: ConfigMap
metadata:
    name: aws-auth
    namespace: kube-system
data:
    mapRoles: |
        - rolearn: arn:aws:iam::022452219843:role/amazonEKSNodeRole
          username: system:node:{{EC2PrivateDNSName}}
          groups:
            - system:bootstrappers
            - system:nodes

    mapUsers: |
        - groups:
          - eks-console-dashboard-restricted-access-group      
          userarn: arn:aws:iam::022452219843:user/salihbozkaya
          username: gilabci
