apiVersion: v1
kind: Secret
metadata:
    name: regcred
    namespace: server
type: kubernetes.io/dockerconfigjson

data:
    .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImJtRjBhV05oWkdWMlpXeHZjRzFsYm5RNloyOXZaMnhsTVRBd01RPT0iCgkJfQoJfQp9
