export enum Routes {
    REGISTER = "/register",
    LOGIN = "/login",
    ME = "/me",
    VENDOR_REGISTER = "/vendor-register",
    RESET_PASSWORD = "/reset-password",
    REFRESH_TOKEN = "/refresh-token",
    FILE_UPLOAD = "/file-upload",
    CREATE_VENDOR = "/vendor/create-vendor",
    CREATE_VENDOR_REGION = "/vendor/create-vendor-region",
    CREATE_BUYER = "/buyer/create-buyer",
    CREATE_BUYER_SITE = "/buyer/create-buyersite",
    CREATE_DEALER = "/dealer/create-dealer",
    CREATE_DEALER_SITE = "/dealer/create-dealersite",
    CREATE_VENDOR_DEALER = "/vendor-dealer/create-vendor-dealer",
    CREATE_DEALER_BUYER = "/vendor-dealer/create-vendor-dealer",
}
